<?php
// api/download_question.php - 문제 다운로드
session_start();
require_once '../config/database.php';
require_once '../includes/auth.php';

requireAuth();

if (!isset($_GET['id'])) {
    http_response_code(400);
    exit('문제 ID가 필요합니다.');
}

try {
    $questionId = (int)$_GET['id'];
    $db = new Database();
    $pdo = $db->getConnection();
    
    $stmt = $pdo->prepare("
        SELECT title, question_text, answer_text, created_at 
        FROM questions 
        WHERE id = ? AND user_id = ?
    ");
    $stmt->execute([$questionId, $_SESSION['user_id']]);
    $question = $stmt->fetch();
    
    if (!$question) {
        http_response_code(404);
        exit('문제를 찾을 수 없습니다.');
    }
    
    // 텍스트 파일 내용 생성
    $content = "GPT 문제 메이커 - " . $question['title'] . "\n";
    $content .= "생성일: " . date('Y-m-d H:i:s', strtotime($question['created_at'])) . "\n";
    $content .= str_repeat("=", 50) . "\n\n";
    $content .= "【 문 제 】\n\n";
    $content .= $question['question_text'] . "\n\n";
    $content .= str_repeat("-", 50) . "\n\n";
    $content .= "【 정 답 】\n\n";
    $content .= $question['answer_text'] . "\n\n";
    $content .= str_repeat("=", 50) . "\n";
    $content .= "Generated by GPT 문제 메이커\n";
    
    // 다운로드 헤더 설정
    header('Content-Type: text/plain; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $question['title'] . '.txt"');
    header('Content-Length: ' . strlen($content));
    
    echo $content;
    
} catch (Exception $e) {
    error_log("Download question error: " . $e->getMessage());
    http_response_code(500);
    exit('다운로드 중 오류가 발생했습니다.');
}
?>
